packages:
  - 'apps/*'
  - 'packages/*'
  - 'demo-inference-server/*'

catalogs:
  node:
    typescript: ^5.8.3
    tsx: ^4.19.4
    tsc-alias: ^1.8.16
    '@types/node': ^22.15.17

  react19:
    react: ^19.1.0
    react-dom: ^19.1.0
    '@types/react': ^19.1.3
    '@types/react-dom': ^19.1.3

  trpc:
    '@trpc/client': ^11.1.2
    '@trpc/server': ^11.1.2

  data:
    drizzle-orm: ^0.38.4
    pg: ^8.15.6
    '@types/pg': ^8.15.1
    better-auth: ^1.2.7
    zod: ^3.24.4
    superjson: ^2.2.2

  date:
    date-fns: ^4.1.0
    dayjs: ^1.11.13

  tailwind:
    tailwindcss: ^4.1.7
