apiVersion: v1
kind: Service
metadata:
  name: template-inference-service
  namespace: template-inference-ns
  labels:
    app: template-inference-server
spec:
  type: ClusterIP # Exposes the service on an internal IP in the cluster
  selector:
    app: template-inference-server
  ports:
    - protocol: TCP
      port: 80 # Port the service will be available on within the cluster
      targetPort: 8080 # Port your application container is listening on
