services:
  studio-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '1234:1234'
    environment:
      - NODE_ENV=production
      - CORS_ORIGIN=${CORS_ORIGIN}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

volumes:
  postgres_data:
    driver: local
